### ISSUE TITLE
SyntaxError executing a template

### ISSUE THREAD

**Issue by kitajchuk** [Squarespace/template-compiler#1]
When executing against template files/partials for a Squarespace site I get the following error:

```shell
SyntaxError PREDICATE_UNKNOWN at line 1 character 1085: Predicate \'folder?\' is unknown
```

I guess one question is whether this is fully ready to use on a Squarespace site template? The README doesn't have any information on usage. Any insights would be awesome :D

**Comment by phensley** [comment]
This project is the core template compiler, but is extensible via plugins (formatters, predicates).  It comes with a small set of plugins, but most of the actual formatters and predicates used by Squarespace are currently not included with the template compiler, due to their dependencies on internal code. 

Take a look at the `CorePredicates` class you can see a way to write your own custom predicate implementations, if that helps.

**Comment by kitajchuk** [comment]
Okay, cool. I just wasn't sure if I should expect this to have the Squarespace predicates or not. Now I know. Thanks man :)

**Comment by phensley** [comment]
Cool, I'll close this for now, but will reopen it when we can unwind some of the dependencies and release the rest of the plugins.
